language: perl

matrix:
    include:
        - os: linux
	  dist: trusty
	  perl: 5.24
	- os: linux
	  perl:
  		- "5.24"
  		- "5.22"
  		- "5.20"
  		- "5.18"
  		- "5.16"
  		- "5.14"
  		- "5.08"
	- os: osx

install: true

script: cd bin ; ./mh -tk 0 -code_dir ../code/test
